# The size of a fixed type
LIBFIXED_BITWIDTH ?= 16

# Changes how precise certain functions are (i.e. sin, cos)
LIBFIXED_PRECISE ?=

# Number of bits reserve for fractional part of number
LIBFIXED_FRAC_BITWIDTH ?= 5

# Do integer arithmetic for testing purposes
LIBFIXED_TEST ?=
