# This makefile applies the options.
# For list of options and documentation see Makefile.config

ifneq ($(LIBFIXED_PRECISE),)
override CFLAGS += -DCONFIG_PRECISE=1
endif

ifneq ($(LIBFIXED_TEST),)
override CFLAGS += -DCONFIG_TEST=1
endif

override CFLAGS += -DCONFIG_BITWIDTH=$(LIBFIXED_BITWIDTH)
override CFLAGS += -DCONFIG_FRAC_BITWIDTH=$(LIBFIXED_FRAC_BITWIDTH)
